### ISSUE TITLE
Create a subworkflow for functional analysis methods

### ISSUE THREAD

**Issue by suzannejin** [nf-core/differentialabundance#384]
# Tasks

Some work is done in branch `dev-ratio`, now following the effort in nf-core/differentialabundance#341, we want to:

- [x] Clean the code for such subworkflow (it calls functional analysis methods like GSEA and gProfiler2)
- [x] Add tests
- [x] Add it to nf-core/modules as component

# Additional tasks

- [x] nf-core/modules#7200

**Comment by suzannejin** [comment]
Ongoing work in 

- [x] nf-core/modules#7254

**Comment by suzannejin** [comment]
Waiting for the update of the upstream modules/subworkflows:

- [x] nf-core/modules#7258

- [x] nf-core/modules#7302

- [x] nf-core/modules#7265

- [x] nf-core/modules#7266

**Comment by suzannejin** [comment]
close with nf-core/modules#7254 and #431
